apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: apache
  name: apache
  namespace: dev
spec:
  replicas: 2
  selector:
    matchLabels:
      app: apache
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: apache
    spec:
      containers:
      - image: httpd:2.4.55
        name: httpd
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: '100Mi'
            cpu: '25m'
          limits:
            memory: '100Mi'
            cpu: '25m'
status: {}
